# Generated by Django 4.2.4 on 2023-08-29 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('link', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.product'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.product'),
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
