# Generated by Django 4.2.4 on 2023-09-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='link_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
