# Generated by Django 4.2.4 on 2023-08-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_product_alter_order_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
