# Generated by Django 4.2.4 on 2023-09-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_purchase_link_id_remove_purchase_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
