# Generated by Django 4.1 on 2023-09-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='link_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
