# Generated by Django 4.1 on 2023-09-29 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_link_id_alter_order_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_by_email', to='bot.user'),
        ),
    ]
