# Generated by Django 4.1 on 2023-09-29 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_email_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='context',
        ),
        migrations.AlterField(
            model_name='user',
            name='emails',
            field=models.ManyToManyField(blank=True, related_name='emails', to='bot.email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_email', to='bot.email'),
        ),
    ]
