# Generated by Django 4.1 on 2023-09-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_alter_order_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='link_id',
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name='user',
            name='emails',
            field=models.ManyToManyField(blank=True, to='bot.email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_email',
            field=models.EmailField(blank=True, default='12@gmal.com', max_length=255, unique=True),
        ),
    ]
