# Generated by Django 4.1 on 2023-09-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
