# Generated by Django 4.1 on 2023-09-30 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_alter_order_options_order_primary_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='primary_email',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_email_order', to='bot.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
    ]
