# Generated by Django 4.1 on 2023-09-30 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_alter_order_primary_email_alter_user_primary_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='primary_email',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_email_order', to='bot.email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_email',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_primary_email', to='bot.email'),
        ),
    ]
