# Generated by Django 4.1 on 2023-09-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_remove_order_primary_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_email',
            field=models.EmailField(blank=True, default='12@gmal.com', max_length=255, unique=True),
        ),
    ]
