# Generated by Django 4.1 on 2023-09-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0028_alter_order_options_alter_user_primary_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(max_length=255),
        ),
    ]
