# Generated by Django 4.1 on 2023-09-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0034_rename_user_id_order_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
