# Generated by Django 4.1 on 2023-09-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0035_alter_order_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_name',
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(default=123321, on_delete=django.db.models.deletion.CASCADE, related_name='orders_by_user', to='bot.user'),
        ),
    ]
