# Generated by Django 4.1 on 2023-09-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0039_order_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='link_id',
            field=models.IntegerField(),
        ),
    ]
