# Generated by Django 4.1 on 2023-09-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0041_link_link_number_alter_link_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='link_number',
        ),
        migrations.AddField(
            model_name='link',
            name='id',
            field=models.CharField(default='none', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='link_id',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
