# Generated by Django 4.1 on 2023-09-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0042_remove_link_link_number_link_id_alter_link_link_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_id',
            field=models.CharField(max_length=255),
        ),
    ]
