# Generated by Django 4.1 on 2023-09-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0044_alter_link_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='link_id',
        ),
    ]
