# Generated by Django 4.1 on 2023-09-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0045_remove_link_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link_id',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
